name = "Perms"
uuid = "64ad0214-35bc-4c2a-8d3a-e394312c55ba"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.0"

[compat]
julia = "1"
Combinat = v"0.0.3,0.0.4,0.0.5"
Primes = "0.5.3, 0.6"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Combinat = "a6b051d1-fc4b-4ede-b53e-347fa9fb9a74"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
